### ISSUE TITLE
Сannot get a Identified Files report for large projects: reach the innerElementCountThreshold:50000

### ISSUE THREAD

**Issue by kkalesnikava** [blackducksoftware/sdk-client-tools-protex#29]
I have a big project that needs to be scanned. After the scan is complete, I need to get **Identified Files** report using api. 

In order to try to get a report, I decided to use **example SampleReportDataIdentifiedFiles.** Because the project is very big, I get the following error:

```
SampleReportDataIdentifiedFiles failed
javax.xml.ws.soap.SOAPFaultException: reach the innerElementCountThreshold:50000
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:158)
	at com.sun.proxy.$Proxy52.getEffectiveIdentifications(Unknown Source)
	at report.SampleReportDataIdentifiedFiles.main(SampleReportDataIdentifiedFiles.java:93)
Caused by: org.apache.cxf.binding.soap.SoapFault: reach the innerElementCountThreshold:50000
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.unmarshalFault(Soap11FaultInInterceptor.java:84)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:51)
	at org.apache.cxf.binding.soap.interceptor.Soap11FaultInInterceptor.handleMessage(Soap11FaultInInterceptor.java:40)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:113)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:69)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:34)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:849)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1642)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1520)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1317)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:632)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:572)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:481)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:382)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:335)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:136)
	... 2 more
Caused by: org.apache.cxf.binding.soap.SoapFault: reach the innerElementCountThreshold:50000


> Task :SampleReportDataIdentifiedFiles.main() FAILED

```

The error occurs because variable `fileNodes` has a value greater than 50000. Which means that the following line cannot be executed:
```
List<CodeTreeIdentificationInfo> idInfos = identificationApi.getEffectiveIdentifications(projectId, fileNodes); 
```

If there is any way to fix it and get Identified Files report  for large projects?

Link to the `SampleReportDataIdentifiedFiles.java` example can be found [here](https://github.com/blackducksoftware/sdk-client-tools-protex/blob/master/protex-sdk-examples/src/main/java/com/blackducksoftware/sdk/protex/client/examples/report/SampleReportDataIdentifiedFiles.java), line 119.

**Comment by romeara** [comment]
One workaround might be to split the `fileNodes` list into smaller sub-lists and use them with `getEffectiveIdentifications`, then combine the results at the end - this would prevent fileNodes from overflowing the CXF inner element limit

**Comment by kkalesnikava** [comment]
@romeara, thanks for your proposal but it doesn't help me. The number of my `fileNodes` is about 60000. So I decided to use in the report only`FILES` NodeTypes:

` codeTreeParameters.getIncludedNodeTypes().add(FILE);`

instead of this:

`codeTreeParameters.getIncludedNodeTypes().addAll(CodeTreeUtilities.ALL_CODE_TREE_NODE_TYPES);`

In this case, I have a fileNodes number of about 48000, but currently I have the following exception:
```
SampleReportDataIdentifiedFiles failed
com.blackducksoftware.sdk.fault.SdkFault: "(class org.springframework.transaction.TransactionSystemException) - Could not roll back JPA transaction; nested exception is javax.persistence.PersistenceException: unexpected error when rollbacking" - Exception with error code "None" is not properly converted - Please open a support ticket report with Black Duck Software.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.cxf.interceptor.ClientFaultConverter.processFaultDetail(ClientFaultConverter.java:182)
	at org.apache.cxf.interceptor.ClientFaultConverter.handleMessage(ClientFaultConverter.java:82)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultChainInitiatorObserver.java:113)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:69)
	at org.apache.cxf.binding.soap.interceptor.CheckFaultInterceptor.handleMessage(CheckFaultInterceptor.java:34)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:849)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1642)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1520)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1317)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:632)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:572)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:481)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:382)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:335)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:136)
	at com.sun.proxy.$Proxy52.getEffectiveIdentifications(Unknown Source)
	at report.SampleReportDataIdentifiedFiles.main(SampleReportDataIdentifiedFiles.java:112)

> Task :SampleReportDataIdentifiedFiles.main() FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':SampleReportDataIdentifiedFiles.main()'.
```

This issue is again related to the following line in SampleReportDataIdentifiedFiles.java :
`List<CodeTreeIdentificationInfo> idInfos = identificationApi.getEffectiveIdentifications(projectId, fileNodes);`

**Comment by romeara** [comment]
That appears to be a server-side error (specifically with respect to interacting with the application's database). Your best bet for that specific error is to send a message to support with that exception trace and the application version. Sorry I can't provide anything more direct to try :(
